Integration with AI/ML API
VRSEN/agency-swarm pull request #189
Opened 2024-11-29 09:04 UTC by waterstark

Hi!
I am a Python developer working at AI/ML API.
This PR is intended to explain to users how they can connect to our service.

2025-01-06 09:05 UTC, waterstark commented
Hi, could you let me know the status of the pull request? Is there anything that needs to be adjusted for it to be accepted?

2025-02-05 21:35 UTC, bonk1t requested changes

2025-02-05 21:35 UTC, bonk1t commented on docs/advanced-usage/open-source-models.md
> +            # model = You can visit our website https://aimlapi.com and choose from over 200 models to suit your preferences.
"You can visit our website https://aimlapi.com" - was this written by you? @waterstark
looks like an ad

2025-02-12 14:45 UTC, waterstark commented on docs/advanced-usage/open-source-models.md
> +            # model = You can visit our website https://aimlapi.com and choose from over 200 models to suit your preferences.
Hi @bonk1t ,
I’m not entirely sure I understood your comment, but just in case, I’ve changed that line to the default one. Let me know if there’s anything else I should adjust!

2025-02-12 20:17 UTC, bonk1t approved these changes

2025-02-12 20:18 UTC, merged